[package]
name = "kanime-api-v3"
version = "0.1.1"
edition = "2021"
description = "Kanime API V3 Server"
publish = false

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10.0"

[profile.release]
lto = "thin"